apiVersion: v1
kind: Service
metadata:
  name: nextclouddb
spec:
  ports:
    - port: 3306
  selector:
    app: nextclouddb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextclouddb
spec:
  serviceName: nextclouddb
  replicas: 1
  selector:
    matchLabels:
      app: nextclouddb
  template:
    metadata:
      labels:
        app: nextclouddb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.7.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "vNp2UH7ZAR"
            - name: MYSQL_DATABASE
              value: "nextcloud"
            - name: MYSQL_USER
              value: "nextcloud"
            - name: MYSQL_PASSWORD
              value: "gE0bnJbonxcpH2uq"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

